=== Customization
==== Keycloak
If you need some auth server, in our case it's https://www.keycloak.org[Keycloak] execute following commands inside *environment repository folder*.

* add Keycloak chart
```shell
jx gitops helmfile add --chart=vitech-sdlc/keycloak --namespace=keycloak --repository=https://vitech-team.github.io/sdlc-charts
```
* resolve main helmfile
```shell
jx gitops helmfile resolve
```
* create new branch and create PR
* wait for green pipelines
* merge PR

==== Oauth access for Pipelines dashboard
Default setup is configured for *GitHub*, if you need change your auth provider check: https://jenkins-x.io/v3/admin/setup/ingress/oauth/

==== Domain & TLS configuration
https://jenkins-x.io/v3/admin/setup/ingress/tls_dns/

==== Pipelines
===== Pipelines catalog and pack
All shared tasks and packs are stored in: https://github.com/vitech-team/tekton-pipelines-catalog.

===== Packs
Custom packs: https://github.com/vitech-team/tekton-pipelines-catalog/tree/master/packs.

All tasks, packs and pipelines are managed by syncing to https://github.com/vitech-team/jx3-gke-vault[environment repository] via https://googlecontainertools.github.io/kpt/[Kpt].

NOTE: For more information about tasks and pipelines, check https://github.com/tektoncd/pipeline[Tekton docs].

NOTE: For more information about pipelines on JX, see https://jenkins-x.io/docs/v3/develop/pipeline-catalog/[JX Pipeline Docs].

==== Large Tests

Currently, we have only Large Tests implementation based on https://webdriver.io[WebdriverIO].
We have added a few steps to `release` and `pullrequest` pipelines:

* Check if the large test has been executed on *Staging* before promote it to Production *environment*.
* Execute *Large Tests* after changes applied on Production environment.

===== Enable

* Open `.lighthouse/large-test/triggers.yaml` and change: `always_run: false`, `optional: false` to `true`.
* Open `.lighthouse/jenkins-x/release.yaml` and uncomment commented tasks: ` large-test-prepare-and-check` and `large-test-execute`.
** Change large test image name property: `LARGE_REPORTS_IMAGE`.
** Change your app URLs properties: `APP_URL_STAGING`, `APP_URL_PRODUCTION`. If you have more environments, just add additional property like: `APP_URL_XXX`.

===== Selenium
For selenium hub config, use:

* `charts/dev/largetests/values.yaml.gotmpl`.
* `charts/dev/largetests/values.yaml`.

List of all configs: https://github.com/helm/charts/tree/master/stable/selenium#configuration.

===== Slack notifications
If you want to edit Large test execution message in slack, please open and add changes: `charts/dev/secret/templates/slack-messages.yaml`.

NOTE: You can use following variables that can be populated/replaced: `${ENV}`, `${STATUS}`, `${REPORT_URL}`, `${DETAILS}` and `${GIT_SHA}`.


==== Keycloak

* For Keycloak configuration, use: `charts/dev/keycloak/values.yaml.gotmpl` file in env. repository list of keycloak configs: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#configuration.
* For default realm configuration in <<runbook-vault>>, find `keycloak-relams/efault-relam.json` key and edit existed json.
** If you need to add more realms, add new realm secret into `charts/dev/keycloak/templates` and configure in `charts/dev/keycloak/values.yaml`.

==== Metrics
Metrics chart https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack[kube-prometheus-stack].

* For custom monitors and gradana dashboard, use the folder: `charts/dev/prometheusmonitors/templates`.
* For metrics stack configuration, use:
** `charts/prometheus-community/kube-prometheus-stack/values.yaml.gotmpl`.
** `charts/prometheus-community/kube-prometheus-stack/values.yaml`.

==== Alertmanager
===== Configure Slack notifications
* In <<runbook-vault>> find `alertmanager.yaml` secret and replace `${SLACK_HOOK_URL}` with your hook URL. Example: `charts/prometheus-community/kube-prometheus-stack/secret-schema.yaml`.

==== Runbook

[[runbook-cluster-delte]]
===== Сluster delete

* For the cluster, delete `cd` from your infra repository and execute `terraform destroy`.

[[runbook-vault]]
===== Vault

* For port forward Vault type: `jx secret vault portforward`. After that you can access Vault at: https://localhost:8200.
* Vault root token can be found in secret: `vault-unseal-keys`, key: `vault-root`.

[[runbook-keycloak]]
====== Keycloak
* Keycloak url: `kubectrl get ingress -n keycloak`.
