VITech Software Development Life Cycle Manual

This document is created to represent our SDLC. Our development process is effective, modern, scalable, and lightweight. Our methods make us competitive compared with other top-performing companies, we can work fast without losing efficiency. We can deliver value to customers minimizing the failures and creating a blame-free environment. We keep our employees motivated, satisfied, and inspired by using modern and effective tools and processes. We save money by reducing the development period. We collect, share and reuse knowledge. We create an atmosphere of trust and constant self-improving.


NOTE: Inspired by https://www.goodreads.com/book/show/35747076-accelerate[Accelerate]

== Overview
Current solution is built on top of https://jenkins-x.io[Jenkins X]. 

NOTE: Jenkins X aims to automate and accelerate Continuous Integration and Continuous Delivery for developers on the cloud and/or Kubernetes allowing them to focus on building awesome software instead of figuring out how to use the cloud or manually create and maintain pipelines.


=== Architecture
==== Simple view
++++
<iframe style="border:none" width="100%" height="550px" src="https://whimsical.com/embed/DGQcqfVJMY5CuP4z2QGU1s"></iframe>
++++

==== Extended
++++
<iframe style="border:none" width="100%" height="850px" src="https://whimsical.com/embed/8GKYgDts1C3ZKb3ccsrzpR"></iframe>
++++

=== CI/CD flow
++++
<iframe allowfullscreen frameborder="0" style="width: 100%; height: 750px;" src="https://lucid.app/documents/embeddedchart/88013d3c-9451-45de-b97c-87e3bf8dff8a" id="ZddTO1PVGjTd"></iframe>
++++

==== Pull Request flow
* https://www.conventionalcommits.org/en/v1.0.0/[conventional commits] scan - https://github.com/aevea/commitsar[Commitsar]
* scan for secrets - https://github.com/zricethezav/gitleaks[Gitleaks]
* build - including <<#small-test>> & <<#medium-test>>
* dependencies check - https://owasp.org/www-project-dependency-check/[OWASP Dependency-Check]
* container build - using https://paketo.io[Paketo Buildpacks] or https://github.com/GoogleContainerTools/kaniko[Kaniko]
* container scan - https://github.com/aquasecurity/trivy[Trivy] & https://github.com/goodwithtech/dockle[Dockle]
* static code analyse - https://www.sonarqube.org[sonar]
* preview environment creation - JX (preview folder in imported project)

=== Stack
* https://jenkins-x.io[Jenkins X] - CORE
* https://tekton.dev[Tekton] - CI/CD
* https://kubernetes.io[Kubernetes]
* https://www.terraform.io[Terraform]
* https://www.keycloak.org[Keycloak] - Open Source Identity and Access Management
* https://webdriver.io[WebdriverIO] - Large test framework
